#include "declarations.h"

void initPortA (void) {
	SYSCTL_RCGCGPIO_R |= 0x01;
	while ((SYSCTL_PRGPIO_R & 0x01)==0) {}
	
	GPIO_PORTA_LOCK_R = 0x4C4F434B;
	GPIO_PORTA_CR_R = 0xFF;
	GPIO_PORTA_AFSEL_R |= 0x03;
	GPIO_PORTA_PCTL_R |= 0X11;
	GPIO_PORTA_AMSEL_R &= ~(0X03);
	GPIO_PORTA_DEN_R |= 0x03;
}

void initPortB (void) {
	SYSCTL_RCGCGPIO_R |= 0x02;
	while ((SYSCTL_PRGPIO_R & 0x02)==0) {}
	
	GPIO_PORTB_LOCK_R = 0x4C4F434B;
	GPIO_PORTB_CR_R = 0xFF;
	GPIO_PORTB_AFSEL_R |= 0x03;
	GPIO_PORTB_PCTL_R |= 0x11;
	GPIO_PORTB_AMSEL_R = 0x00;
	GPIO_PORTB_DEN_R |= 0x03;
}

void initPortF (void) {
	SYSCTL_RCGCGPIO_R |= 0x20;
	while ((SYSCTL_PRGPIO_R & 0x20)==0) {}
	
	GPIO_PORTF_LOCK_R = 0x4C4F434B;
	GPIO_PORTF_CR_R = 0x1F;
	GPIO_PORTF_AFSEL_R = 0x00;
	GPIO_PORTF_PCTL_R = 0x00;
	GPIO_PORTF_AMSEL_R = 0x00;
	GPIO_PORTF_DIR_R |= 0x0E;
	GPIO_PORTF_DEN_R |= 0x1F;
	GPIO_PORTF_PUR_R |= 0x11;
	GPIO_PORTF_DATA_R = 0x00;
		
}


